<template>
   <div id="multiplayer">
       <div id="nav">
           <router-link to="/">Home</router-link>
       </div>

    <p>Enter room code and a nickname</p>

       <!-- skriv in rumskod -->
       <!-- Göra om till form?-->
       <input type="text" placeholder="Enter room code" v-model="room" >
       <input type="text" placeholder="Enter nickname" v-model="nickname" >
       <button @click="submit()" >Submit</button>

       <p> {{responseText}} </p>

       <div v-if="loading" class="loading">
           Loading...
       </div>


       <div id="roomInfo" v-show="showRoomInfo">

    <p>Welcome to room {{room}} {{nickname}}</p>
    <p>You will answer {{gamecode.length}} questions</p>
       <router-link
               :to="{name: 'multiPlay', params:{gc : gamecode, nickname : nickname, room : room} }" class="startButton" tag="button" > Start!
       </router-link>

   </div>


   </div>
</template>

<script>

    export default {
        name: "multiplayer",
        data() {
            return {
                room: "",
                nickname: "",
                gamecode: [],
                tempData: "",
                responseText: "",
                showRoomInfo: false,
                loading: false
            }
        },
        methods: {
            submit: function () {

                var nickName = this.nickname;
                var roomName = this.room;

                if (/\s/.test(nickName)) {
                    this.responseText = "No spaces in your nickname please"
                } else if (!nickName) {
                    this.responseText = "You dont have a name?"
                }
                else if (!roomName){
                    this.responseText = "You need to name the room you want to join"
                }else {
                    this.responseText = ""
                    this.loading = true;

                    /*skapa spelare*/
                    fetch('https://fierce-mountain-27289.herokuapp.com/v1/createplayer', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({"room": this.room, "nickname": this.nickname}),
                        // info är ett element som vi postar body
                    })
                        .then(response => response.json())
                        .then(data => {


                            if(data.info == "Nickname already exists") {
                                this.responseText = data.info
                                this.loading = false
                            }
                            else if(data.info == "Room not found") {
                                this.responseText = data.info
                                this.loading = false
                            }
                            else{
                                /*hämta spelkod*/

                                var url = new URL('https://fierce-mountain-27289.herokuapp.com/v1/room')
                                var params = {room: this.room}
                                url.search = new URLSearchParams(params).toString()

                                fetch(url, {
                                    method: 'GET',
                                    headers: {
                                        'Content-Type': 'application/json',
                                    }
                                })
                                    .then(response => response.json())
                                    .then(data => {
                                        console.log('Success:', data);
                                        this.tempData = data.gamecode;
                                        this.gamecode = this.tempData.split(",");
                                        this.gamecode.shift();
                                        // shift removes first empty element in array, generated by split

                                        this.showRoomInfo = true;
                                        this.loading = false;
                                    })
                                    .catch((error) => {
                                        console.error('Error:', error);

                                    });
                            }
                        })
                        .catch((error) => {
                            console.error('Error:', error);
                        });
                    console.log(JSON.stringify({"room": this.room, "nickname": this.nickname}))




                }

            }
        }
    }
</script>

<style scoped>
#multiplayer{
    height: 1000px;
    background-repeat: no-repeat;
    background-image: url("../../public/kids.jpg");
    background-size: 100%;
}
    button{
        cursor: pointer;

    }

</style>